name: Parse Logs & Update static site

on:
  push:
    branches: [ master ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET preview
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.201'

      - name: Build site
        run: |
          dotnet publish -c Release -o published -p:BlazorEnableCompression=false ./src/view/DIPolWeb.csproj

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Produce log
        run: |
          source("./R/write_fixed.R")
          source("./R/proc_duf.R")
          source("./R/proc_dp2.R")
          source("./R/proc.R")
        shell: Rscript {0}

      - name: Upload results
        uses: actions/upload-artifact@main
        with:
          name: obslogs
          path: output

      - name: Fixing GH Pages
        run: |
          touch ./published/wwwroot/.nojekyll
          mkdir ./published/wwwroot/sample-data
          cp ./output/obslog.json ./published/wwwroot/sample-data/obslog.json
          Get-Content ./published/wwwroot/index.html | % {[System.Text.RegularExpressions.Regex]::Replace($_, "<base\s*href=`"/`"/>", "<base href=`"/obslogs/`"/>")} > ./published/wwwroot/index2.html
          mv -f ./published/wwwroot/index2.html ./published/wwwroot/index.html
        shell:
          pwsh


      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: published/wwwroot
          SINGLE_COMMIT: true

