name: Parse Logs & Update static site

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Build site
        run: | 
          dotnet publish -c Release -o published -p:BlazorEnableCompression=false ./src/view/view.csproj
       
      - name: Set up R
        uses: r-lib/actions/setup-r@v1

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ hashFiles('.github/R-version') }}-1-

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
        shell: Rscript {0}
      
      - name: Produce log
        run: |
          source("./R/write_fixed.R")
          source("./R/proc_duf.R")
          source("./R/proc_dp2.R")
          source("./R/proc.R")
        shell: Rscript {0}
      
      - name: Upload results
        uses: actions/upload-artifact@main
        with:
          name: obslogs
          path: output

      - name: Fixing GH Pages
        run: |
          touch published/wwwroot/.nojekyll
          mkdir published/sample-data
          cp output/obslog.json published/sample-data/obslog.json
          ls published
          ls published/sample-data


      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: published/wwwroot
          SINGLE_COMMIT: true

